create table UserDetails (
ID Varchar NOT NULL,
NAME Varchar(30) NOT NULL,
EMAIL_ID Varchar(30) NOT NULL,
PASSWORD Varchar(30) NOT NULL,
IMAGE VARCHAR,
CONSTRAINT PK_User PRIMARY KEY (ID),
CONSTRAINT UC_User UNIQUE (EMAIL_ID)
);